### ISSUE TITLE
WSSSPE4 report: purpose of the Code of Conduct section

### ISSUE THREAD

**Issue by bangerth** [WSSSPE/meetings#134]
Reading through the WSSSPE4 report/draft, I wonder who the audience of the report is going to be, and what purpose the section on the Code of Conduct serves. (I'm not questioning the CoC at all -- I think it was a great idea). The way it is presented suggests that it applied to the Workshop itself, and as such it may not be of great interest to readers of the report, in the same way as we typically don't include the schedule of talks for workshop reports -- they're an organizational detail that is no longer relevant after the workshop is over.

On the other hand, it may be that the intent of the CoC is not just to apply to the workshop itself, but to the *community* as well. In that case, it may be useful to rewrite a few sentences leading up to the quote to make that clear. I can do the rewriting if so desired, but wanted to ask what the intention was.

(I'm also curious what the mentioned incident was -- because I think I could learn something from it --, but maybe a public forum is inappropriate to ask this?)

**Comment by kyleniemeyer** [comment]
@bangerth From my understanding, the specific CoC applied just to the workshop—although generalizing it to all WSSSPE community spaces would be a great idea!

One purpose of the workshop report is to describe how the workshop was organized and run, and so we wanted to include mention of the CoC (which was new to WSSSPE4) with things like the call for participation. This is done in part to document all aspects of the workshop, for members of the community, the funders who supported the workshop, and other interested parties. So, in that sense, while it is an organizational detail, I don't think it isn't relevant after the workshop.

**Comment by kyleniemeyer** [comment]
As far as the incident mentioned, I think it is ok to describe without mentioning any names: in brief, the initial mechanism for holding speakers to their allotted time was to hug them if they went over, which made some attendees uncomfortable. This was removed after the first day after someone pointed this out to the CoC committee.

**Comment by kyleniemeyer** [comment]
At this point, I'll wait for @danielskatz and/or others to chime in, but I certainly agree that the CoC adopted for WSSSPE4 should be extended to the community as a whole, and if so the section of the report could be extended slightly to reflect that.

**Comment by bangerth** [comment]
OK, thanks for the explanation @kyleniemeyer . I'll wait for @danielskatz and will be happy to rephrase the section to match that the CoC is supposed to cover the community.

**Comment by danielskatz** [comment]
@bangerth please go ahead and do this - sorry for the delay...

**Comment by danielskatz** [comment]
@bangerth Can you do this in the next couple of days?

**Comment by danielskatz** [comment]
@bangerth ping...
