### ISSUE TITLE
WSSSPE3 report: citation vs. footnote for links?

### ISSUE THREAD

**Issue by kyleniemeyer** [WSSSPE/meetings#75]
This question may be more important once the initial draft of the WSSSPE3 report is completed, but does anyone have any suggestions on when to prefer footnotes or citations for links? 

Following the WSSSPE2 report, I began using footnotes for a number of links, but also saw some in the reference list... so I ended up using a mix.

**Comment by danielskatz** [comment]
I think that in the WSSSPE2 report, we tried to use references for things we intended to cite, and footnotes for things that were just notes.  Whether or not those “things” were URLs didn’t matter.

But I’m open for changes for the WSSSPE3 report…

Maybe URLs that are just notes should be in-line (in parens)?

Dan

> On Oct 28, 2015, at 7:52 AM, Kyle Niemeyer <notifications@github.com> wrote:
> 
> This question may be more important once the initial draft of the WSSSPE3 report is completed, but does anyone have any suggestions on when to prefer footnotes or citations for links?
> 
> Following the WSSSPE2 report, I began using footnotes for a number of links, but also saw some in the reference list... so I ended up using a mix.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/WSSSPE/meetings/issues/75>.
> 

-- 
Daniel S. Katz
University of Chicago
(773) 834-7186 (voice)
(773) 834-6818 (fax)
d.katz@ieee.org <mailto:d.katz@ieee.org> or dsk@uchicago.edu <mailto:dsk@ci.uchicago.edu>
http://www.ci.uchicago.edu/~dsk/ <http://www.ci.uchicago.edu/~dsk/>

**Comment by sctchoi** [comment]
I would think if it is a webpage or a blog post, then it is better for 
it to be a REFERENCE item.

**Comment by kyleniemeyer** [comment]
I'm leaning toward references as well, if only because inline URLs might clutter the text, and footnotes are starting to accumulate. (I recognize that I'm responsible for a good amount of this.)

I suppose there could be a distinction between citing a webpage with the intent of referencing information on that webpage, and using a footnote just as an indication to where someone could go if they are interested (the current practice, I believe).

**Comment by danielskatz** [comment]
Unless we get some other people with opinions, let's go with references mostly.

**Comment by danielskatz** [comment]
closing this since the report is done for now
